#!/bin/bash

here=`pwd`
parent="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
topdir=$parent/..
cd $topdir

PATH=$topdir/tools:$PATH

set -e

version=`version normal`
lastrev=`version revision`
major=`version major`
minor=`version minor`
micro=`version micro`

# increment the appropriate version number
if [ "$1" = "micro" ]; then
   micro=`expr $micro + 1`
elif [ "$1" = "minor" ]; then
   minor=`expr $minor + 1`
   micro="0"
elif [ "$1" = "major" ]; then
   major=`expr $major + 1`
   minor="0"
   micro="0"
else
   echo "Invalid version bump: major minor or micro"
   exit 1
fi

versionnext=$major.$minor.$micro
echo Bumping version from $version to $versionnext


# actually update the version file

echo $versionnext.`version commit` > "$topdir/tools/version.txt"
git commit -am "Bump `version normal`"

cd $here

version=`version normal`
if [ "$version" != "$versionnext" ]; then
    echo Version bump failed, version mismatch
    exit 1;
fi

echo "Finished";
exit 0
